function coursebook(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',ec='.cache.html',_='/',lb='//',Xb='42E189F047321ACA0EB0F25D0AD25CB4',Zb='4F540864057D200198CC946F3EC5B3ED',$b='647E5E89CB589090347D535C8F253244',_b='67C747B236984A557C78138A3090B086',ac='8599A84BC4F0DE00B548AB3323EE9CA1',dc=':',Yb=':1',pb='::',mc='<script defer="defer">coursebook.onInjectionDone(\'coursebook\')<\/script>',hb='<script id="',sb='=',$='?',bc='B2B7307832BC5FBC46AADF30CBDF3EAB',ub='Bad handler "',lc='DOMContentLoaded',cc='E92DC36950087A4032C70230DE800537',jb='SCRIPT',gb='__gwt_marker_coursebook',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',rb='content',Q='coursebook',eb='coursebook.nocache.js',ob='coursebook::',Fb='datetime',Y='end',Rb='gecko',Sb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',kc='head',Vb='hosted.html?coursebook',jc='href',Qb='ie6',Pb='ie8',Ob='ie9',yb='iframe',ab='img',Db='input',zb="javascript:''",gc='link',Ub='loadExternalRefs',mb='meta',Bb='moduleRequested',X='moduleStartup',Nb='msie',Ib='n',nb='name',Kb='opera',Ab='position:absolute;width:0;height:0;border:none',hc='rel',Mb='safari',db='script',Wb='selectingPermutation',R='startup',ic='stylesheet',Cb='supportsDateTimeInput',Gb='text',fc='timebox.css',Eb='type',fb='undefined',Tb='unknown',Jb='user.agent',Lb='webkit',Hb='y';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}coursebook=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){try{var b=document.createElement(Db);b.setAttribute(Eb,Fb);return b.type!==Gb?Hb:Ib}catch(a){return Ib}};v[Cb]={n:0,y:1};w[Jb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Kb)!=-1}())return Kb;if(function(){return b.indexOf(Lb)!=-1}())return Mb;if(function(){return b.indexOf(Nb)!=-1&&n.documentMode>=9}())return Ob;if(function(){return b.indexOf(Nb)!=-1&&n.documentMode>=8}())return Pb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Qb;if(function(){return b.indexOf(Rb)!=-1}())return Sb;return Tb};v[Jb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};coursebook.onScriptLoad=function(){if(I){r=true;C()}};coursebook.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Ub,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Vb;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Wb});if(!B()){try{G([Ib,Kb],Xb);G([Hb,Kb],Xb);G([Ib,Kb],Xb+Yb);G([Hb,Kb],Xb+Yb);G([Ib,Pb],Zb);G([Hb,Pb],Zb);G([Ib,Pb],Zb+Yb);G([Hb,Pb],Zb+Yb);G([Ib,Qb],$b);G([Hb,Qb],$b);G([Ib,Qb],$b+Yb);G([Hb,Qb],$b+Yb);G([Hb,Mb],_b);G([Ib,Mb],ac);G([Ib,Ob],bc);G([Hb,Ob],bc);G([Ib,Ob],bc+Yb);G([Hb,Ob],bc+Yb);G([Ib,Sb],cc);G([Hb,Sb],cc);G([Ib,Sb],cc+Yb);G([Hb,Sb],cc+Yb);K=x[H(Cb)][H(Jb)];var M=K.indexOf(dc);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+ec}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[fc]){var a=n.createElement(gc);__gwt_stylesLoaded[fc]=a;a.setAttribute(hc,ic);a.setAttribute(jc,t+fc);n.getElementsByTagName(kc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(lc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(lc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Ub,millis:(new Date).getTime(),type:T});n.write(mc)}
coursebook();